// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DevDefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCF-MNQZDPz7e_yqT3GSZaDvek3t-1O9I',
    appId: '1:1030299345488:android:c886a6ef8c7f9039efe755',
    messagingSenderId: '1030299345488',
    projectId: 'dev-help1',
    storageBucket: 'dev-help1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaAWpTslC31eclpCFkYp6T7gfNUraMrK4',
    appId: '1:1030299345488:ios:19987d9391567657efe755',
    messagingSenderId: '1030299345488',
    projectId: 'dev-help1',
    storageBucket: 'dev-help1.appspot.com',
    androidClientId:
        '1030299345488-6nk4euo6pj0onnmlsts2npbdcaepcrp6.apps.googleusercontent.com',
    iosClientId:
        '1030299345488-c5b5s289tvt4m705ceigljhi6ejo3cet.apps.googleusercontent.com',
    iosBundleId: 'com.help1.mobile.dev',
  );
}
