// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DevDefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DevDefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DevDefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DevDefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DevDefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DevDefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DevDefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-MBUWlE1AR7uswfNmddRPcOdHT4loQxY',
    appId: '1:570560561302:android:327c245ed4826f824902b7',
    messagingSenderId: '570560561302',
    projectId: 'sitesurface-flutter-starter',
    storageBucket: 'sitesurface-flutter-starter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuDrX6vW-lHDjrKPaEO56hB1KDuDAaLLg',
    appId: '1:570560561302:ios:94d4fd64f52769a54902b7',
    messagingSenderId: '570560561302',
    projectId: 'sitesurface-flutter-starter',
    storageBucket: 'sitesurface-flutter-starter.appspot.com',
    androidClientId: '570560561302-aj917fkgjfdngcj4hpluu9tpbijtcovr.apps.googleusercontent.com',
    iosClientId: '570560561302-glj0n69qf2oauc68mqr103d73riln71j.apps.googleusercontent.com',
    iosBundleId: 'com.sitesurface.starter.dev',
  );
}
