name: sitesurface_flutter_starter_project
description: Flutter Starter Project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  

  # UI
  concentric_transition: ^1.0.3

  # notification
  flutter_local_notifications: ^13.0.0

  # icons and fonts
  material_design_icons_flutter: ^6.0.7096
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

  # network
  http: ^0.13.5
  connectivity_plus: ^3.0.2
  webview_flutter: ^4.0.1

  # firebase dependencies
  firebase_app_check: ^0.1.1+8
  cloud_firestore: ^4.3.1
  firebase_performance: ^0.9.0+9
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.10
  firebase_dynamic_links: ^5.0.11
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  firebase_crashlytics: ^3.0.9
  firebase_remote_config: ^3.0.9
  firebase_in_app_messaging: ^0.7.0+10

  # authentication
  flutter_facebook_auth: ^5.0.7
  sms_autofill: ^2.2.0
  sign_in_with_apple: ^4.3.0
  google_sign_in: ^5.4.3
  crypto: ^3.0.2
  intl_phone_field: ^3.1.0


  # image and media
  image_picker: ^0.8.6
  flutter_svg: ^1.1.6
  flutter_image_compress: ^1.1.3
  cached_network_image: ^3.2.3
  lottie: ^2.1.0

  # loading...
  shimmer: ^2.0.0
  bot_toast: ^4.0.3
  flutter_native_splash: ^2.2.16

  # state management and cache
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  shared_preferences: ^2.0.15

  # location
  geolocator: ^9.0.2

  # miscellanious
  path_provider: ^2.0.11
  intl: ^0.17.0
  path: ^1.8.2
  share_plus: ^6.3.0
  in_app_review: ^2.0.6
  equatable: ^2.0.5
  package_info_plus: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.3
  freezed: ^2.3.2
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  web:
    generate: false
  windows:
    generate: false
  remove_alpha_ios: true
  image_path: "assets/icons/app_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_logo.png"

flutter_native_splash:
  color: "#ffffff"
  backgroundColor: "#ffffff"
  image: "assets/icons/app_logo.png"
  android: true
  ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/lottie/

